version: '2'
services:
  mysql:
    image: 'mysql:latest'
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=fab014
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=agenda-petshop
    volumes: 
      - '../docker_db:/var/lib/mysql'
  flyway:
    image: flyway/flyway
    command: 'migrate'
    volumes:
      - ./infrastructure/migrations/config:/flyway/conf
      - ./infrastructure/migrations/sql:/flyway/sql
    depends_on:
      - mysql